apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "yetibot.fullname" . }}
  labels:
    {{- include "yetibot.labels" . | nindent 4 }}
data:
  # Sample Yetibot config. Populate these values (at minimum configure an
  # adapter) with your own config or secrets.
  # merge env and overrideenv - ensuring keys from env - which are in overrideenv are overridden
  {{- $env := mergeOverwrite .Values.yetibot.env .Values.yetibot.overrideenv }}
  {{- range $key, $value := $env }}
    {{ $key }}: "{{ $value }}"
  {{- end }}
