{{- if .Values.manageSecrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "yetibot.fullname" . }}
  labels:
    {{- include "yetibot.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": before-hook-creation
type: Opaque
data:
  # fill in with your configuration values. these will show up as env vars in
  # the pod. see:
  # https://github.com/yetibot/yetibot.core/blob/master/config/sample.env
  # for the full list.
{{- end }}
