
name: Handle repository dispatch events

# this allows other repos to send a release dispatch here which then triggers a
# version bump
on:
  repository_dispatch:
    types: [release]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: debug
        run: echo ${{ github.event.client_payload.message.docker_tag }}
